# Generated by Django 3.2.8 on 2021-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('avg', models.IntegerField(verbose_name='معدل')),
                ('grade', models.CharField(max_length=50, verbose_name='مقطع تحصیلی')),
                ('field_study', models.CharField(max_length=50, verbose_name='رشته تحصیلی')),
                ('university', models.CharField(max_length=50, verbose_name='دانشگاه')),
                ('education_place', models.CharField(max_length=50, verbose_name='محل تحصیل')),
            ],
        ),
    ]
