# Generated by Django 3.2.8 on 2021-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='degree_education',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='مدرک تحصیلی'),
        ),
    ]
